Non-clearcase builds work now, some view-private files are being lost though

diff --git a/work/nightly/runbuild b/work/nightly/runbuild
--- a/work/nightly/runbuild
+++ b/work/nightly/runbuild
@@ -1,13 +1,11 @@
 #!/bin/bash
 
 print_usage() {
-    echo "Usage: runbuild [ -e | --email <address> ] [ -c | --ccbuild ] <source script>"
+    echo "Usage: runbuild [-h|--help] [-e|--email <address>] <source script>"
 }
 
 EMAIL=
 EMAIL_SET=false
-
-CCBUILD_SET=false
 
 BUILDSRC=
 BUILDSRC_SET=false
@@ -15,10 +13,6 @@ BUILDSRC_SET=false
 while [ -n "$1" ]
 do
     case "$1" in
-
-        -c | --ccbuild)
-            CCBUILD_SET=true
-            ;;
 
         -e | --email)
             EMAIL_SET=true
@@ -47,15 +41,15 @@ if [ "$BUILDSRC_SET" == "false" ]; then
     exit 1
 fi
 
-if [ "$CCBUILD_SET" == "true" ]; then
-    # Reset this view back to default; gets rid of all view-private files, among
-    # other things
-    view-default
+if [ -f "$BUILDSRC" ]; then
+    # Source the given build script and save the return code
+    . "$BUILDSRC" > /tmp/build.out.$$ 2> /tmp/build.error.$$
+    RETURN="$?"
+else
+    # Evaluate BUILDSRC as it must be a command
+    eval "$BUILDSRC" > /tmp/build.out.$$ 2> /tmp/build.error.$$
+    RETURN="$?"
 fi
-
-# Source the given build script and save the return code
-. "$BUILDSRC" > /tmp/build.out.$$ 2> /tmp/build.error.$$
-RETURN="$?"
 
 # Move the build output files into wherever we are now
 mv /tmp/build.out.$$ build.out
